version: "3.7"

services:
    postgres:
        build:
            context: .
            args:
                - BASE_IMAGE_TAG=$DOCKER_TAG
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - 5433:5432
    
    sut:
        build: ./tests
        depends_on:
            - postgres