version: "3.7"

services:
    postgres:
        build:
            context: .
            args:
                - BASE_IMAGE_TAG=$DOCKER_TAG
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - 5432:5432
    
    sut:
        image: governmentpaas/psql
        command: /tests/run.sh
        depends_on:
            - postgres
        volumes:
            - ./tests:/tests