version: "3.7"

services:
    sut:
        build:
            context: .
            args:
                - BASE_IMAGE_TAG=$DOCKER_TAG
        command: psql postgres -U postgres -a -f /tests/create_extensions.sql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - ./tests:/tests