version: "3.7"

services:

    postgres:
        # image: ivanlonel/postgis-with-extensions:latest
        build:
            context: . # Use image from Dockerfile in current dir
            args:
                - BASE_IMAGE_TAG=latest
        command:
            - postgres
            - -c
            - effective_cache_size=2048MB
            - -c
            - shared_buffers=256MB
            - -c
            - work_mem=8MB
            - -c
            - maintenance_work_mem=256MB
            - -c
            - track_counts=on
            - -c
            - autovacuum=on
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
            - TZ=America/Sao_Paulo
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./postgres-passwd:/run/secrets/postgres-passwd
        networks:
            - pgnetwork

    powa-web:
        image: powateam/powa-web
        restart: always
        ports:
            - 8888:8888
        environment:
            - TZ=America/Sao_Paulo
        networks:
            - pgnetwork
        depends_on:
            - postgres

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        ports:
            - 80:80
        environment:
            - PGADMIN_DEFAULT_EMAIL
            - PGADMIN_DEFAULT_PASSWORD
            - TZ=America/Sao_Paulo
        volumes:
            - pgadmin4_data:/var/lib/pgadmin
            - ./servers.json:/pgadmin4/servers.json
        networks:
            - pgnetwork
        depends_on:
            - postgres

volumes:
    postgres_data:
    pgadmin4_data:

networks:
    pgnetwork:
        driver: bridge
