version: "3.7"

services:
    postgres:
        build:
            context: .
            args:
                - BASE_IMAGE_TAG=$DOCKER_TAG
        environment:
            - LANG=pt_BR.utf8
            - LC_COLLATE=C
            - POSTGRES_PASSWORD=postgres
            - TZ=America/Sao_Paulo
        networks:
            - pgtest_network
        ports:
            - "5432:5432"

    sut:
        build: ./tests
        command:
            - "/tests/wait-for-postgres.sh"
            - "postgres"
            - "psql"
            - "postgresql://postgres:postgres@postgres:5432/postgres"
            - "-a"
            - "-f"
            - "/tests/create_extensions.sql"
        depends_on:
            - postgres
        environment:
            - POSTGRES_PASSWORD=postgres
        networks:
            - pgtest_network

networks:
    pgtest_network:
        driver: bridge