# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  schedule:
    # postgis update schedule is '15 5 * * 1'
    # https://github.com/postgis/docker-postgis/blob/master/.github/workflows/main.yml
    - cron: '15 7 * * 1'

env:
  REGISTRY: ghcr.io
  TEST_TAG: ${{ github.repository }}:test
  COMPOSE_FILE: ./docker-compose.test.yml

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: read

    strategy:
      fail-fast: false
      matrix:
        postgis_image_tag:
          - latest
          - 14-master
          - 14-3.1
          - 13-master
          - 13-3.1
          - 13-3.0
          - 12-master
          - 12-3.1
          - 12-3.0
          - 12-2.5
          - 11-3.1
          - 11-3.0
          - 11-2.5

    env:
      BUILD_ARGS: |
        BASE_IMAGE_TAG=${{ matrix.postgis_image_tag }}
        LOCALE=pt_BR
        ENCODING=UTF-8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: ${{ matrix.postgis_image_tag }}
          
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          no-cache: true
          pull: true
          tags: ${{ env.TEST_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ env.BUILD_ARGS }}

      - name: Build test stack
        env:
          IMAGE_NAME: ${{ env.TEST_TAG }}
        run: docker compose up --build --no-start

      - name: Run tests
        env:
          IMAGE_NAME: ${{ env.TEST_TAG }}
        run: docker compose start sut

      - name: Log in to container registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push to registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ env.BUILD_ARGS }}

      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ${{ steps.meta.outputs.tags }}
          dst: |
            docker.io/${{ github.repository }}:${{ matrix.postgis_image_tag }}

      - name: Update Docker Hub description
        if: ${{ github.event_name != 'pull_request' }}
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
